version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2-sdk
      
    working_directory: ~/repo

    steps:
      - checkout
      - dotnet build
      - run:
          name: XUnit Tests
          command: dotnet test MyProject.Test